[config]
schemaVersion = "0.0.1"

[package]
namespace = "SGG_Modding"
name = "ModUtil"
versionNumber = "2.10.0"
description = "Utility mod for mod interactions within lua for for SGG's games"
websiteUrl = "https://github.com/SGG-Modding/ModUtil"
containsNsfwContent = false

[package.dependencies]
SGG_Modding-ModImporter = "1.6.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]
